openapi: 3.0.1
info:
  title: Books Store API
  description: API Definition of Books Store API
  version: 1.0.0
servers:
  - url: "http://localhost:8290"
paths:
  /books:
    get:
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookList'
    post:
      requestBody:
        description: Add Book
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
          
  /books/{id}:
    get:
      parameters:
        - name: id
          in: path
          description: 'ID of the book'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
    put:
      parameters:
        - name: id
          in: path
          description: 'ID of the book'
          required: true
          schema:
            type: string    
      requestBody:
        description: Update Book
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Book'      
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
    delete:
      parameters:
        - name: id
          in: path
          description: 'ID of the book'
          required: true
          schema:
            type: string    
      responses:
        200:
          description: Default response  
          
components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        title:
          type: string
          example: Java for dummies
        author:
          type: string
          example: mark
    BookList:
      type: array
      items:
        $ref: '#/components/schemas/Book'
    
       